version: '3'
services:
  jekyll:
  #  image: starefossen/github-pages
    build: .
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: bind
        source: ./~sites
        target: /_site
    tty: true

# To run rake locally
# docker exec -i gcweb-reorg_jekyll-with-env-options_1 rake
